### ISSUE TITLE
Rad Studio 11 Problem

### ISSUE THREAD

**Issue by celibol** [Delphier/DxAutoInstaller#13]
If compile DevExpres Ver 19.1.2 with DxAutoInstaller cxLibraryRS28.bpl give too many errors.

For Ex:

1. dxBarManager does not edit Toolbars (With Edit Dialog) (I Think cxLibrary bpl has compile error)

2. if run cxShellBrowser.execute then give Access Violation error

Because some controls not created

For Ex: 
liCurrentFolder.CaptionOptions.Text := cxGetResourceString(@scxShellBrowserDlgCurrentFolderCaption); (cxshellBrowser.pas at line 139)

liCurrentFolder.CaptionOptions is nil

**Comment by celibol** [comment]
cxGrid does not custumize grid

**Comment by celibol** [comment]
Solved

All of the errors solved (Testing now)

Solve:
1. Go to dxForms.Pas (expressLibrary\Sources directors)
2. Find ReadState Function
3. Add inherited to first line

Recompile and install

**Comment by gss200610** [comment]
(TcxImageComboBoxItems) show blank forms, only recompilation manual dclcxLibrary solve. so, this remove all packages installed
