### ISSUE TITLE
Error when executing DxAutoInstaller

### ISSUE THREAD

**Issue by eduardorff** [Delphier/DxAutoInstaller#15]
I selected all devexpress components and tryed to install them. Then I received the error on the image below. Could someone help me?
"dxCoreRS27.dpk(63) Fatal: F2613 Unit 'dxCore' not found. Compilation failure Error."

**Comment by alan008** [comment]
Just run DxAutoInstaller with Administrator privileges, as it need to copy all *.pas files into Library subfolder.
