### ISSUE TITLE
XP Theme Manager is not recognized even if it exists

### ISSUE THREAD

**Issue by ertankucukoglu** [Delphier/DxAutoInstaller#19]
Hello,

In the selected directory, there is "XP Theme Manager" exactly as written in here and three files in its Sources folder
dxThemeConsts.pas
dxThemeManager.pas
dxUxTheme.pas

But, it is listed as not available in DxAutoInstaller v2.3.5. This is not just this folder but other folders, too. All of them exists with "Sources" folders and files inside.
![image](https://user-images.githubusercontent.com/14805520/236157572-574e7845-813b-4753-895f-e8c4be74e5ee.png)

I could not understand what is missing and why DxAutoInstaller cannot identify these folders.

**Comment by Delphier** [comment]
These packages have been merged into the ExpressLibrary (the cxLibraryRS~ packages)  since v18.2.2: https://supportcenter.devexpress.com/versionhistory#BC4618
