### ISSUE TITLE
DxInstaller Doesn't compile DevExPrinting System Teechart connector if Teechart Standard Is no Installed

### ISSUE THREAD

**Issue by fduenas** [Delphier/DxAutoInstaller#2]
Hi What are the conditions that DxAutoinstaller must check to compile Dx Printing System Teechart Link, because I have Installed Teechart pro, I have neverinstalled Teechart Standard version from Delphi Installer. 

So when I run DxAutoInstaller The Teechart Link is never compiled.
Does the DxInstaller Check domethign in the regsitry or something I'm Missing?

**Comment by Delphier** [comment]
DxAutoInstaller does not detect TeeChart Pro, so...
