### ISSUE TITLE
x64 install fail.

### ISSUE THREAD

**Issue by 104979058** [Delphier/DxAutoInstaller#23]
![QQ截图20231122090406](https://github.com/Delphier/DxAutoInstaller/assets/28974521/e2680b6e-1c7c-4a37-97ba-0439592a3359)
![QQ截图20231122090506](https://github.com/Delphier/DxAutoInstaller/assets/28974521/e4eef3db-1f34-4e65-b3da-30e0776d733e)
x64 install fail.

**Comment by Delphier** [comment]
Looking at the error message, it appears to be a code issue. Is it the official source code?

**Comment by 104979058** [comment]
> Looking at the error message, it appears to be a code issue. Is it the official source code? What's DxAutoInstaller and Delphi version?

delphi Rad studio 12
Dev VCL 23.14
win11 x64

**Comment by Delphier** [comment]
DevExpress VCL v23.2.1 version starts to support Delphi12.
