### ISSUE TITLE
Tools doesnt support current IDE !!

### ISSUE THREAD

**Issue by quicksoftdz** [Delphier/DxAutoInstaller#24]
hello,
im trying to install the **DevExpress**  **v23.1.4** for the Delphi 12 version but the tools mark the checkboxes by red and tell that current IDE is not supported !.
IDE version: Delphi 12 Version 29.0.50491.5718 
![Uploading Capture d’écran 2023-11-24 161353.png…]()

**Comment by zinpub** [comment]
> hello,
> im trying to install the **DevExpress**  **v23.1.4** for the Delphi 12 version but the tools mark the checkboxes by red and tell that current IDE is not supported !.
> IDE version: Delphi 12 Version 29.0.50491.5718 
> 
> 

Devexpress 23.1.4 dont support Delphi 12

**Comment by quicksoftdz** [comment]
i tested it with the DevExpress v22.1.3 and it give the same error !!

**Comment by Delphier** [comment]
Only v23.2.1+ supports Delphi12:
![](https://user-images.githubusercontent.com/6134731/284932736-3a7caf71-9515-4c7a-b408-dc7ed644da33.png)

**Comment by quicksoftdz** [comment]
thanks a lot, can you send us manuall install step by step?
we have source code
