### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by xxFALKORxx** [Delphier/DxAutoInstaller#26]
Recently donwload Devexpress VCL, zip file comes with DXAutoinstaller. When i execute it, list components is empty. Do i need to execute it from an specific folder?

**Comment by xxFALKORxx** [comment]
> Recently donwload Devexpress VCL, zip file comes with DXAutoinstaller. When i execute it, list components is empty. Do i need to execute it from an specific folder?

never mind

**Comment by zinpub** [comment]
There is EditBox for source path
