### ISSUE TITLE
What is the purpose of this project?

### ISSUE THREAD

**Issue by raelb** [Delphier/DxAutoInstaller#3]
Hi,
Since DevExpress VCL comes with it's own installer, I did not understand the purpose of this project. Please clarify?
Thanks
Rael

**Comment by Delphier** [comment]
Maybe some people don't want to use the official installer, or not 😊

**Comment by leus** [comment]
This installer is way more convenient than DevExpress own installer. In my old job we preferred to use this because we could organize source code better in our source code repository.
