### ISSUE TITLE
Default checkbox hides enabled settings

### ISSUE THREAD

**Issue by JayDi85** [Delphier/DxAutoInstaller#4]
By default installer tries to install in all available IDEs. If user want to select one IDE then unchecks unwanted options. BUT some hidden options are enabled by default -- that's make installer to install in unwanted IDE. That's wrong. You must inform/cofirm about selected IDE before install.

![shot_190816_040821](https://user-images.githubusercontent.com/8344157/63135127-96314600-bfdd-11e9-88a3-7d8e95fc3e56.png)

**Comment by Delphier** [comment]
@JayDi85 Yes, this is a bug, thank you for your feedback.

**Comment by Delphier** [comment]
Fixed in 797f707
