### ISSUE TITLE
Bpl & Dcp Path Error

### ISSUE THREAD

**Issue by ricleon** [Delphier/DxAutoInstaller#5]
The path obtained during program installation is incorrect. Why?
\Bpl
\Dcp
Removing from registry package \Bpl\dxCoreRS14.bpl
Unregistration failed
Deleing BPL Files: \Bpl\dxCoreRS14.*
Deleing DCP Files: \Dcp\dxCoreRS14.*
……
Compiling package D:\OtherControl\D2010\Dev18.1.6\ExpressCore Library\Packages\dxCoreRS14.dpk
"C:\Program Files (x86)\Embarcadero\RAD Studio\7.0\bin\dcc32.exe" "D:\OtherControl\D2010\Dev18.1.6\ExpressCore Library\Packages\dxCoreRS14.dpk" --no-config -U"C:\Program Files (x86)\Embarcadero\RAD Studio\7.0\lib" -DDEBUG; -U"\Dcp;" -LN"\Dcp" -LE"\Bpl"  -$D- -$L- -$Y- -Q  -U"\Dcp" -U"D:\OtherControl\D2010\Dev18.1.6\Library\Sources" -R"D:\OtherControl\D2010\Dev18.1.6\Library\Sources"  -B -NU"D:\OtherControl\D2010\Dev18.1.6\Library\RS14" -N0"D:\OtherControl\D2010\Dev18.1.6\Library\RS14" -AWinTypes=Windows;WinProcs=Windows;DbiTypes=BDE;DbiProcs=BDE -NSWinapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell;System;Xml;Data;Datasnap;Web;Soap;IBX;VclTee;  -DUSENATIVELOOKANDFEELASDEFAULT 
Embarcadero Delphi for Win32 compiler version 21.0
Copyright (c) 1983,2009 Embarcadero Technologies, Inc.
D:\OtherControl\D2010\Dev18.1.6\Library\Sources\dxUriRecord.pas(221) Warning: W1063 Widening given AnsiChar constant (#$A0) to WideChar lost information
D:\OtherControl\D2010\Dev18.1.6\Library\Sources\dxUriRecord.pas(667) Warning: W1063 Widening given AnsiChar constant (#$9F) to WideChar lost information
D:\OtherControl\D2010\Dev18.1.6\Library\Sources\dxUriRecord.pas(667) Warning: W1063 Widening given AnsiChar constant (#$9F) to WideChar lost information
Fatal: F2039 Could not create output file '\Bpl\dxCoreRS14.bpl'
Compilation failure
Error.

**Comment by Delphier** [comment]
This is a known issue only on Delphi 2010, it seems that Delphi 2010 incorrectly marks the default Bpl and Dcp path, please send all environment variables of your Delphi 2010.
