### ISSUE TITLE
RunningError: 'Format '%s***%s***'invalid or incompatible with argument.

### ISSUE THREAD

**Issue by yilinghl** [Delphier/DxAutoInstaller#6]
![cap](https://user-images.githubusercontent.com/54854149/76854610-60fa1880-688a-11ea-976e-9e2d406badbc.PNG)

**Comment by jeffovercash** [comment]
That one is actually a JEDI error.  You'll need to update JEDI to include the latest IDEs (probably 10.4 in this case)

**Comment by jeffovercash** [comment]
The JCL has been updated (well at least nightly builds) so getting that resolves this after a rebuild.

https://github.com/project-jedi/jcl

**Comment by Delphier** [comment]
Fixed in JCL(20250910): https://github.com/project-jedi/jcl/commit/00ce0d03b718a886413e8b2bfb844b49afde8398#diff-c2ade4fe9b06341808de3916e1838443a3fe47eccb8fb131ba079fd94b6f69a4:~:text=Result%20%3A%3D%20Format(%27%25s%20***%25d***%27%2C%20%5BRadToolName%2C%20IDEVersionNumber%5D)%3B
