### ISSUE TITLE
Unable to create directory

### ISSUE THREAD

**Issue by yilinghl** [Delphier/DxAutoInstaller#7]
When I make install the DX. it shows "Unable to create directory"
and stop.
![Capture](https://user-images.githubusercontent.com/54854149/76855274-c1d62080-688b-11ea-9d4b-5e21637756dc.PNG)

![Capture2](https://user-images.githubusercontent.com/54854149/76855345-e7fbc080-688b-11ea-9687-b3ccde010871.PNG)

**Comment by yilinghl** [comment]
system is  Win7 64bit.
but it's OK on Win10

**Comment by Delphier** [comment]
Have a try run DxAutoInstaller as Administrator.

**Comment by yilinghl** [comment]
I'm sure that I running it as Administrator. and try to remove(uncheck) the read only attributes of any files and folder of DX .

and try to make a larger free space of disk.

I search this problem on the internet. someone also got that problem. but another didn't.
I think this is relate to the system. et.al.  WinAPI....  .. but I don't known how to do...

**Comment by Delphier** [comment]
Try the latest version.
